db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: drupal8user
    MYSQL_PASSWORD: drupal8password
    MYSQL_DATABASE: drupal8
web:
  image: touchcast/docker-nginx-php7
  ports:
    - "8888:80"
  volumes:
    - .:/var/www/html
  environment:
    MYSQL_HOST: db:3306
    MYSQL_PASSWORD: drupal8password
