db:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: drupal8user
    MYSQL_PASSWORD: drupal8password
    MYSQL_DATABASE: drupal8
web:
  image: richarvey/nginx-php-fpm
  ports:
    - "8888:80"
  volumes:
    - .:/var/www/html
  links:
    - db:db
  environment:
    MYSQL_HOST: db:3306
    MYSQL_PASSWORD: drupal8password
